name       : python3-ipython
version    : 8.14.0
release    : 19
source     :
    - https://files.pythonhosted.org/packages/source/i/ipython/ipython-8.14.0.tar.gz : 1d197b907b6ba441b692c48cf2a3a2de280dc0ac91a3405b39349a50272ca0a1
homepage   : https://ipython.org/
license    : BSD-3-Clause
component  : programming.python
summary    : IPython provides a rich toolkit to help you make the most of using Python interactively
description: |
    IPython provides a rich toolkit to help you make the most of using Python interactively.
builddeps  :
    - git
    - matplotlib
    - pygments
    - python-backcall
    - python-jedi
    - python-jupyter_core
    - python-nbformat
    - python-nose
    - python-matplotlib-inline
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-pytest-asyncio
    - python-stack-data
    - python-testpath
rundeps    :
    - pygments
    - python-backcall
    - python-jedi
    - python-matplotlib-inline
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-simplegeneric
    - python-stack-data
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    pushd $installdir/usr/lib/python%python3_version%/site-packages
#    pytest -v -k 'not test_ipython_embed'
#    popd
