name       : python3-ipython
version    : 7.25.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/73/fe/0250e9e85629f7eba7182490364174e50c48d1eac98bc5e81f993cf1a11e/ipython-7.25.0.tar.gz : 54bbd1fe3882457aaf28ae060a5ccdef97f212a741754e420028d4ec5c2291dc
homepage   : https://ipython.org/
license    : BSD-3-Clause
component  : programming.python
summary    : IPython provides a rich toolkit to help you make the most of using Python interactively
description: |
    IPython provides a rich toolkit to help you make the most of using Python interactively.
builddeps  :
    - git
    - matplotlib
    - pygments
    - python-backcall
    - python-ipykernel
    - python-nbformat
    - python-nose
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-pytest
    - python-testpath
    - python-traitlets
    - python3-jedi
rundeps    :
    - pygments
    - python-backcall
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-simplegeneric
    - python-traitlets
    - python3-jedi
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/iptest && rm $installdir/usr/bin/ipython
    mv $installdir/usr/share/man/man1/ipython.1 $installdir/usr/share/man/man1/ipython3.1
check      : |
    # No module matplotlib-inline?
    #python3_test pytest3
