name       : python3-ipython
version    : 6.2.1
release    : 5
source     :
    - https://github.com/ipython/ipython/archive/6.2.1.tar.gz : 547aa2eabd05cb6baa9206d2c905396f4e1c327fcf568e9647c50237d2c4888e
license    : BSD-3-Clause
component  : programming.python
summary    : IPython provides a rich toolkit to help you make the most of using Python
    interactively.
description: |
    IPython provides a rich toolkit to help you make the most of using Python interactively.
rundeps    :
    - pygments
    - python-decorator
    - python3-jedi
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-simplegeneric
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/iptest && rm $installdir/usr/bin/ipython
    mv $installdir/usr/share/man/man1/ipython.1 $installdir/usr/share/man/man1/ipython3.1
