name       : python3-ipython
version    : 7.26.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/i/ipython/ipython-7.26.0.tar.gz : 0cff04bb042800129348701f7bd68a430a844e8fb193979c08f6c99f28bb735e
homepage   : https://ipython.org/
license    : BSD-3-Clause
component  : programming.python
summary    : IPython provides a rich toolkit to help you make the most of using Python interactively
description: |
    IPython provides a rich toolkit to help you make the most of using Python interactively.
builddeps  :
    - git
    - matplotlib
    - pygments
    - python-backcall
    - python-matplotlib-inline
    - python-jedi
    - python-jupyter_core
    - python-nbformat
    - python-nose
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-pytest
    - python-testpath
rundeps    :
    - pygments
    - python-backcall
    - python-jedi
    - python-matplotlib-inline
    - python-pexpect
    - python-pickleshare
    - python-prompt-toolkit
    - python-simplegeneric
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/iptest && rm $installdir/usr/bin/ipython
    mv $installdir/usr/share/man/man1/ipython.1 $installdir/usr/share/man/man1/ipython3.1
check      : |
    %python3_test pytest3
